---
openapi: 3.0.0
info:
  title: Teste
  version: 1.0.0
servers:
- url: http://localhost:8080/
paths:
  /resources:
    get:
      description: ""
      responses:
        "200":
          description: ""
          headers:
            Access-Control-Allow-Origin:
              style: simple
              explode: false
              schema:
                type: string
              example: '*'
            Access-Control-Allow-Origin':
              style: simple
              explode: false
              schema:
                type: string
              example: '*'
          content:
            application/json: {}
components: {}
